---
name:             GaitSpeed
main:             presentkim\gaitspeed\GaitSpeed
version:          1.2.2
api:              [3.0.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
author:           PresentKim

permissions:
  gaitspeed.cmd:
    description:  GaitSpeed main command
    default:      op
    children:
      gaitspeed.cmd.default:
        description:  GaitSpeed command - default
        default:      op
      gaitspeed.cmd.set:
        description:  GaitSpeed command - set
        default:      op
      gaitspeed.cmd.list:
        description:  GaitSpeed command - list
        default:      op
      gaitspeed.cmd.lang:
        description:  GaitSpeed command - lang
        default:      op
      gaitspeed.cmd.reload:
        description:  GaitSpeed command - reload
        default:      op
      gaitspeed.cmd.save:
        description:  GaitSpeed command - save
        default:      op
...
